### ISSUE TITLE
What is the meaning of a very high FDR ?

### ISSUE THREAD

**Issue by ademcan** [owenjm/polii.gene.call#1]
Hi Owen,
I was wondering if there is any meaning of very high FDR values. It happens sometimes that the FDR values for a given gene are extremenly high (> 100) and I was wondering if that makes any sense or if it was an error (?).
Thank you for your help.

**Comment by owenjm** [comment]
The FDR is calculated via a series of regressions; it's accurate for low FDRs, but for some very clearly unexpressed genes the FDR obtained through this method can end up being > 1.  Essentially, just consider any FDR value > 1 to equal 1.

I've been meaning to change the code so that the maximum value outputted is 1, thanks for reminding me!

**Comment by ademcan** [comment]
That was also my initial thought. Thank you for the clarifications and your work.

**Comment by owenjm** [comment]
No worries at all!  Glad it's working.
